title: LLMWorkbook
description: "Effortlessly harness the power of LLMs on Excel and DataFrames—seamless, smart, and efficient!"
baseurl: "/LLMWorkbook"
url: "https://aryadhruv.github.io/LLMWorkbook"

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# GitHub Pages specific
repository: aryadhruv/LLMWorkbook

# Site settings
author:
  name: Dhruv Arya
  email: dhruv166arya@gmail.com

# Social links
github_username: aryadhruv

# Navigation
header_pages:
  - documentation.md
  - examples.md

# Collections for proper routing
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
lang: en

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .pytest_cache/
  - __pycache__/
  - .git/
  - .github/
  - llmworkbook/
  - scripts/
  - poetry.lock
  - pyproject.toml
