name: Quality Check

on:
  pull_request:  # Runs on every PR
    branches: [main, master]  # Adjust based on your workflow

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
      - name: Install Project Dependencies
        run: poetry install --only dev
      - name: Run Quality Check Script
        run: |
          poetry add pandas numpy
          chmod +x scripts/code_quality_check.sh
          poetry run ./scripts/code_quality_check.sh llmworkbook
        shell: bash
        continue-on-error: false
      - name: Quality Check Results
        if: failure()
        run: |
          echo "❌ Quality checks failed! Fix the reported issues before merging."
          exit 1
